CREATE TABLE `houses` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL COMMENT '员工编号',
  `location` varchar(255) NOT NULL DEFAULT '' COMMENT '城区.街道.小区',
  `address` varchar(255) NOT NULL DEFAULT '' COMMENT '房源地址',
  `h_expect` int(11) NOT NULL COMMENT '房东最高报价',
  `d_expect` int(11) NOT NULL COMMENT '房东最低报价',
  `agency` varchar(255) NOT NULL DEFAULT '' COMMENT '押金+中介费',
  `decoration` tinyint(11) NOT NULL COMMENT '房屋的装修情况',
  `appliance` tinyint(11) NOT NULL COMMENT '房屋的家具家电',
  `birth` int(11) NOT NULL COMMENT '房屋年代',
  `area` int(11) NOT NULL COMMENT '房屋面积',
  `j_area` int(11) NOT NULL COMMENT '房屋建筑面积',
  `house_type` varchar(255) NOT NULL DEFAULT '' COMMENT '房屋户型',
  `property_structure` varchar(255) NOT NULL DEFAULT '' COMMENT '房屋产权及建筑类型',
  `orientation` varchar(255) NOT NULL DEFAULT '' COMMENT '房屋朝向',
  `storey` varchar(255) NOT NULL DEFAULT '' COMMENT '楼层',
  `loan` tinyint(11) NOT NULL DEFAULT '0' COMMENT '贷款与否',
  `condition` varchar(255) DEFAULT '无' COMMENT '房屋的其他备注条件',
  `contract` varchar(255) DEFAULT '' COMMENT '房屋合同编号',
  `status` tinyint(11) NOT NULL,
  `created` int(11) unsigned NOT NULL,
  `updated` int(11) unsigned NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
